Repository GDG-24-25-KAKAOBANK-Android/GDG-Team2, pull requests merged in 2024-11, with the labels that each got.

#5 [STYLE] 폰트 및 컬러 폴더 마크업
  app/src/main/java/com/gdg/kakaobank/ui/theme/Color.kt
  app/src/main/java/com/gdg/kakaobank/ui/theme/Type.kt
  app/src/main/res/font/pretendard_bold.ttf
  app/src/main/res/font/pretendard_regular.ttf
  app/src/main/res/font/pretendard_semibold.ttf
Labels: 영서🦊, 나현🍀, WEEK01, 🎨Style

#6 [STYLE] 스플래시 화면 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/gdg/kakaobank/MainActivity.kt
  app/src/main/java/com/gdg/kakaobank/ui/theme/Color.kt
  app/src/main/java/com/gdg/kakaobank/ui/theme/Theme.kt
  app/src/main/res/drawable/kakaobank_logo.png
  app/src/main/res/values/colors.xml
  app/src/main/res/values/splash_screen.xml
  app/src/main/res/values/themes.xml
Labels: 영서🦊, WEEK01, 🎨Style

#7 [FEAT] 네비게이션 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/gdg/kakaobank/MainActivity.kt
  app/src/main/java/com/gdg/kakaobank/presentation/HomeScreen.kt
  app/src/main/java/com/gdg/kakaobank/presentation/ListScreen.kt
  app/src/main/java/com/gdg/kakaobank/presentation/MainActivity.kt
  app/src/main/java/com/gdg/kakaobank/presentation/MoreScreen.kt
  app/src/main/java/com/gdg/kakaobank/presentation/TagScreen.kt
  app/src/main/java/com/gdg/kakaobank/presentation/navigator/KakaoNav.kt
  app/src/main/res/drawable/home.png
  app/src/main/res/drawable/list.png
  app/src/main/res/drawable/more.png
  app/src/main/res/drawable/tag.png
  app/src/main/res/values/strings.xml
Labels: 영서🦊, 나현🍀, WEEK01, ⚙️Feature

#11 [Feat] 혜택 페이지 구현
  app/src/main/java/com/gdg/kakaobank/presentation/TagScreen.kt
  app/src/main/res/drawable/ic_nonselected.xml
  app/src/main/res/drawable/ic_selected.xml
  app/src/main/res/drawable/ic_send.xml
Labels: 나현🍀, WEEK02, ⚙️Feature

#12 [Feat] 홈 화면 구현
  app/src/main/java/com/gdg/kakaobank/component/Bank.kt
  app/src/main/java/com/gdg/kakaobank/component/MyBank.kt
  app/src/main/java/com/gdg/kakaobank/presentation/HomeScreen.kt
  app/src/main/res/drawable/bell.xml
  app/src/main/res/drawable/ic_bank.xml
Labels: 영서🦊, WEEK02, ⚙️Feature

#13 [Feat] 전체 화면 구현
  app/src/main/java/com/gdg/kakaobank/presentation/MainActivity.kt
  app/src/main/java/com/gdg/kakaobank/presentation/MoreScreen.kt
  app/src/main/res/drawable/icn_next.xml
Labels: 영서🦊, WEEK02, ⚙️Feature
